 The Acquitted

////
Version: Core Edition

Status: Complete::Staging

Characters: Courtney Weber-Ellington (detective partner), Nina Jezebel Black (detective), Peter Gardner (the acquitted), Jack Bennington (rival sleuth, mentioned not present)
////


== Lead, Robbery Victim #2

After considering which avenues of investigation to pursue, Jezebel and Courtney settle on investigating the victims of the burglaries. Jezebel finds Peter Gardner, a man acquited of murder charges on appeal, to be the most curious of the victims, though perhaps not the most promising lead.

=== Investigation

Jezebel wrapped her fingers on the door of Peter Gardner's apartment. Courtney stood behind her in apprehension.

"What if this guy really did do it?" Courtney whispered.

"You can't really prove anyone did anything. Just line up the details. I can take care of myself. Just observe, if you're nervous."

The peep hole which had a beam of light shining through it suddenly went dark, then the light returned. A door swung open six inches, obstructed by a chain attached to the doorframe.

"Can I help you ladies?" A large man asked. Courtney coughed slightly trying to hide a laugh. At 6'3" and two hundred fifty pounds of muscle, his hiding behind a chain from two women nine inches shorter than him was a comical sight.

"We're investigating a series of break-ins that occurred a few nights ago."

"You cops?"

"Private detectives."

"Which private detectives?"

"Jezebel Black."

*"The Jezebel Black?"*

"My reputation proceeds me. Perhaps not so with my partner, Courtney Ellington. A more recent addition."

"I see. You know I hired a guy named Jack Bennington. A professional rival?"

"A friendly rival. We both try not to step on each other's toes."

"Well, come in. I have some coffee brewing. Burning the midnight oil at the books, but I can take some time to talk to some lady detectives."

Peter's door closed and quickly the chain was freed. The door slid open rapidly after that. "How do you like your coffee?" Peter asked.

"Cream and two sugars," Courtney responded.

"Black," answered Jezebel, leading the way inside.

Peter sat down, waiting for the coffee to brew.

"I'll get straight to the point," Jezebel began, "You were one of the seven burglary cases in the incident Sunday night."

"Seven? I thought there were six."

"I've heard differently. I've been able to compile names from media reports and ran criminal background checks on everyone. I didn't find yours the most suspicious for actual guilt--you were acquitted."

"Damn right I was," Gardner acted defiantly.

"But I thought, given your circumstances, you'd be the most likely to withhold evidence from the police. So let's start with what they stole."

"$7,000 in cash. Didn't you read the police reports?"

"I'll read them once they're larger. No point in reading about an ongoing investigation until it simmers a bit. Let's them do the work for me."

"Wow. You don't waste any time. You come to appreciate that in a woman, locked up like I've been."

"I'd imagine so," Jezebel replied. Courtney watched her pretending to have difficulty making eye contact. She noticed the ruse immediately, it was Jezebel pretending she was having difficulty hiding her inability to keep her eyes off her. It was a trick Jezebel taught Courtney, even though she was engaged at the time.

"I bet your girl doesn't waste time either," Peter responded. "Married to a fella so young?"

Courtney was a tad embarassed. She hoped to much blood had rushed to her face. Gardner seemed tough as nails and confident, both things she liked. But he struck her as the kind of guy more trouble then he was worth. She had no intention of leaving her husband, even for just one night of fun.

"I'm sorry," Peter backed off. "Must have gotten a bit forward in prison. Man learns he's got to take what he wants in a place like that." Peter looked back at Jezebel, who met his gaze straight on. *Rusty my ass, Courtney thought to herself.*

"So... why don't you tell us about prison?" Jezebel continued her approach of giving the impression she was trying to pretend to be uninterested. Fishing for a background, most likely, or perhaps just trying to show off her techniques for Courtney to follow.

"Well, you can't show a moment's weakness, particularly for a model prisoner. The thugs around you, they know the officials like you. They get envious. So you never snitch, you never accept favoritism, less of course it's something they know is your thing, like law books. They respect a man trying to beat the system--even though the know if he wins, he's out and they're not."

"Sounds like prison's almost had a positive effect on your character," Jezebel responded.

"Almost?" Gardner asked. Courtney could see Gardner put big stock on having proved his innocence in a court of law, of being a prison survivor. Jezebel guessed it too.

"You're bitter. Vengeful. It gets you up in the morning. It keeps you going at your law degree. But I've seen many trials Peter. You have to keep your head in control, or a good attorney will spot your weakness. You can't show weakness in court either."

Peter put his hand on his chin to think. A finished pot of coffee gave him an excuse to leave the conversation. Courtney and Jezebel received their coffee as ordered. Gardner's emphasis on being a host only made it more obvious that Jezebel had beaten him somehow, and he was eager to learn why he'd lost so that it wouldn't happen again.

"What do you want?" Gardner asked, trying to get Jezebel to lay her hands on the table.

"How much of you $7000 do you want back?"

"It was tuition. I would say I want it all back, but you're clearly proposing something different."

"You spend your life trying to get back what others stole, pretty soon more life is going out the door then is coming back in. Let me recover what I can, and leave the plotting, the vengeance, the justice all in my hands. Let go. You deserve a chance to put all this behind you, find success in a career, find a good woman."

"Well, if I can't get the money back, that means another low pay crap intern position. I'm qualified to be a paralegal by now, but this damn prison sentence, it's still eating away at my future."

"And if you go out and do something stupid finding this guy, you're in a deeper hole than you started."

"Ok. You're hired, so to speak. Find this guy and kick him in the balls."

"This I can do, I promise you that. But you're going to need to tell us if you withheld any information from the police."

"You are a bold woman," Gardner gritted his teeth.

"You haven't answered my question," Jezebel fired back. Courtney felt some electricity from the air was going to zap something.

"Well... I wouldn't go putting the $7000 in a bank account if I were you."

"Counterfeit? Give me a name."

"Jim Walcott."

"The investment banker?"

"Yeah him. I reported that $7000 stolen so he wouldn't think I figured the bucks were dirty. You still take the case?"

"Yes," smiled Jezebel, "I'll take the case," then without any explanation, she turned and walked out.

Courtney followed her out, a little stunned. When the door shut and she was sure he was out of earshot, she asked, "What will you do?"

"I think I'll let him fantasize about me a few days before I make my move."

"What? H-Him?"

"Yeah... there's just this pent up energy. No doubt hasn't been with a woman in five years."

"Wait, what was all that then about trying to get him to let go of his anger?"

"Oh, he will."

"Jezebel, you can't say you're interested in sleeping with a client."

"He's not a client. He's not holding any payment for me. What have I told you of concordances?"

"Details concord with what is."

"No. It is in concordance with lust that the most erotic men are dangerous men, and it is in concordance with safety that time with dangerous men should be limited. He may last a month. Two if he's lucky."

"I..."

"A soon to be married woman doesn't quite know what to say? Haven't you spent most of your working world in tech startups? Lots of young guys, soon to be rich?"

"I didn't look at my job like that. I was in it because I loved the code. I guess I did snatch one into my bed though, didn't I?"

"You're a catch," Jezebel laughed. "You just don't know how to convey that to someone who's not already paying attention."

"Not like you. You want to take this banker down, don't you?"

"Of course. Now, we could go through the legal system, make a few lawyers rich, get him a few years in jail. But I'd rather hit him where it hurts."

"His package?"

Jezebel's laughter rang throughout the rest of the apartment building. "No, his wallet."


.Up Next
`git checkout jim-walcott`

.Tutorials
****

Git Tutorial `git checkout tutorial`

Crime Dossiers `git checkout dossiers`

Using git for hints, `git checkout hints`

If you wish to purchase a custom inventory `git checkout shopping`

For info how to track custom inventory, `git checkout tutorial`, then search for the git tutorial entitled 'tracking-custom-inventory'

****
